plugins {
	id 'fabric-loom' version '1.7-SNAPSHOT'
	id 'maven-publish'
	id 'signing'
	id 'org.jreleaser' version '1.14.0'
}

version = project.mod_version + "+" + project.minecraft_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url "https://maven.terraformersmc.com/" }
	maven {
		url "https://maven2.bai.lol"
		content {
			includeGroup "lol.bai"
			includeGroup "mcp.mobius.waila"
		}
	}

	maven { url "https://maven.shedaniel.me/" }

	maven {
		url "https://cursemaven.com"
	}

    maven { url 'https://maven.blamejared.com' }
}

loom {
	log4jConfigs.from(file("log4j.xml"))

	runs {
		// This adds a new gradle task that runs the datagen API: "gradlew runDatagen"
		datagen {
			inherit server
			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
			vmArg "-Dfabric-api.datagen.modid=${archives_base_name}"

			runDir "build/datagen"
		}
	}
}

sourceSets {
	main {
		resources {
			srcDirs += [
					'src/main/generated'
			]
		}
	}
}

//fabricApi {
//	configureDataGeneration()
//}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	modImplementation("com.terraformersmc:modmenu:${modmenu_version}") {
		transitive = false
	}

	modCompileOnly "mcp.mobius.waila:wthit-api:fabric-${wthitVersion}"
	modRuntimeOnly "mcp.mobius.waila:wthit:fabric-${wthitVersion}"

	modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:$rei_version"
	modCompileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:$rei_version"
//	modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:$rei_version"

	modCompileOnly "dev.emi:emi-fabric:${emi_version}:api"
	modLocalRuntime "dev.emi:emi-fabric:${emi_version}"

    modImplementation "vazkii.patchouli:Patchouli:${patchouli_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withJavadocJar()
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
			pom {
				name = 'Aequitas'
				description = 'A Minecraft mod for changing and generating items'
				url = 'https://github.com/zelythia/aequitas'
				licenses {
					license {
						name = 'MIT License'
						url = 'https://opensource.org/license/mit'
					}
				}
				developers {
					developer {
						id = 'zelythia'
						name = 'Lukas Z'
						email = 'dev@zelythia.net'
					}
				}
				scm {
					connection = 'scm:git:git://github.com/zelytiha/aequitas.git'
					developerConnection = 'scm:git:ssh://github.com/zelythia/aequitas.git'
					url = 'http://github.com/zelythia/aequitas'
				}
			}
		}
	}

	repositories {
		maven {
			url = layout.buildDirectory.dir('staging-deploy')
		}
	}
}


jreleaser {
	project {
		name = this.project.archives_base_name
        java {
            artifactId = this.project.archives_base_name
        }
	}

	release {
		github {
			checksums = false
			signatures = false
			catalogs = false

			commitAuthor {
				name= "lukas/zelythia"
				email= "dev@zelythia.net"
			}

			changelog {
				external = "CHANGELOG.md"
			}
		}
	}

	signing {
		active = 'ALWAYS'
		armored = true
	}
	deploy {
		maven {
			mavenCentral {
				sonatype {
					active = 'ALWAYS'
					url = 'https://central.sonatype.com/api/v1/publisher'
					stagingRepository('build/staging-deploy')
				}
			}
		}
	}
}

javadoc {
	if(JavaVersion.current().isJava9Compatible()) {
		options.addBooleanOption('html5', true)
	}
}
